---
title: "CS_BABY_BIOME_PHENOTYPE_MERGING_&QC"
author: "Trishla Sinha"
date: "17/02/2023"
last update: "23/02/2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r Loading packages}
rm (list = ls())

#load packages 
library(tidyverse)
library(stringr)
library(vegan)
library(RColorBrewer)
library(wesanderson)
library(ggrepel)
library(mgcv) 
library(reshape2)
library(lme4)
library(pheatmap)

```


```{r MERGING ALL PHENOTYPIC DATA TOGETHER, echo=FALSE}

static_1<-read.delim("~/Desktop/CS Baby Biome/PHENOTYPES/raw/CS_Baby_Biome_DATA_2023_02_23_RC.txt") # static phenotypes downloaded from Redcap in feb 2023
static_2<-read.delim("~/Desktop/CS Baby Biome/PHENOTYPES/raw/CS_Baby_biome_phenotypes_extra_static.txt") # Extra static phenotypes derived from patient record (APGAR scores, P valued for growth)
dynamic<-read.delim("~/Desktop/CS Baby Biome/PHENOTYPES/raw/CS_BABY_BIOME_PHENOTYPES_DIET_EXPOSURES.txt") # Dynamic phenotypes chiefly feeding mode for each timepoint
merged<-list(static_1,static_2,dynamic) %>% reduce(full_join, by='ID_original')
#write.table(merged, "PHENOTYPES_CS_BABY_BIOME_23_02_2023.txt", row.names = T, quote = F, sep = "\t")

```

```{r Generating QC files, echo=FALSE}

setwd("~/Desktop/CS Baby Biome/ANALYSIS")
metaphan<-read.table("~/Desktop/CS Baby Biome/ANALYSIS/CS_BABY_BIOME_MERGED_metaphlan4_17_02_2023.txt",sep='\t', header=T, row.names = 1) 
taxa_transposed=metaphan
taxa_transposed$NCBI_tax_id=NULL
#Transpose and convert into data frame
taxa_transposed=as.data.frame(t(taxa_transposed))

#Now merge IDs file with taxa file
taxa_transposed$NG_ID<-row.names(taxa_transposed)
taxa_transposed$NG_ID<- substr(taxa_transposed$NG_ID, 0, 13) 
taxa_transposed<-taxa_transposed[,c(2975, 1:2974)]

# Remove duplicated samples (already checked PCA, look exactly the same)
taxa_transposed<-taxa_transposed[!grepl("D26_1M0662D3", taxa_transposed$NG_ID),] # Known aliquot duplicate
taxa_transposed<-taxa_transposed[!grepl("D4526W06F59G7", taxa_transposed$NG_ID),] # not W6 (clusters differently from other time points but not clear sample swap)
taxa_transposed<-taxa_transposed[!grepl("D4500W05F54A4", taxa_transposed$NG_ID),]# Isolation duplicate 
taxa_transposed<-taxa_transposed[!grepl("D4500M06F54A6", taxa_transposed$NG_ID),]# Isolation duplicate 
taxa_transposed<-taxa_transposed[!grepl("D4501W06X01A4", taxa_transposed$NG_ID),]# Isolation duplicate 
taxa_transposed<-taxa_transposed[!grepl("D4501W06F36E3", taxa_transposed$NG_ID),]# Isolation duplicate 
taxa_transposed<-taxa_transposed[!grepl("D4502M06F36F3", taxa_transposed$NG_ID),]# Isolation duplicate 
taxa_transposed<-taxa_transposed[!grepl("D4503W01F36G5", taxa_transposed$NG_ID),]# Isolation duplicate 
taxa_transposed<-taxa_transposed[!grepl("D4504M06F36H2", taxa_transposed$NG_ID),]# Isolation duplicate
taxa_transposed<-taxa_transposed[!grepl("D4504W05F36G9", taxa_transposed$NG_ID),]# Isolation duplicate

# Rename the sample which was mislabelled as W1 but its the mom from that samples 
taxa_transposed$NG_ID[grepl("D4526W01F59G6",taxa_transposed$NG_ID)]<-"D4526MOMF59G6"  # Also checked on PCOA, outlier in infant PCA, clusters well with mothers 
taxa_transposed$NG_ID[grepl("D26_2M0662D4_",taxa_transposed$NG_ID)]<-"D4526M0662D4" # Renaming sample with odd name 
row.names(taxa_transposed)<-taxa_transposed$NG_ID
taxa_transposed$NG_ID=NULL
taxa_transposed<- as.data.frame(taxa_transposed)
row.names (taxa_transposed)  <- str_replace(row.names (taxa_transposed)  , "_", "")

sequenced<-taxa_transposed[,1:2]
sequenced$k__Archaea=NULL
sequenced$CS_BABY_BIOME_ID<-substr(row.names(sequenced), 0, 5) 
sequenced$CS_BABY_BIOME_ID <- str_replace(sequenced$CS_BABY_BIOME_ID , "A", "D")

n_occur <- data.frame(table(sequenced$CS_BABY_BIOME_ID)) # To check that there are absolutely no more duplicates 


ab=read.table("~/Desktop/CS Baby Biome/ANALYSIS/ANTIBIOTIC_STATUS_CS_BABY_BIOME_22_02_2023.txt",sep='\t', header=T)
names (ab)[2]<-"CS_BABY_BIOME_ID"
dna<-read.delim("~/Desktop/CS Baby Biome/QC/CS_Baby_Biome_all_QC_22_02_2023.txt")
dna<-dna[,1:2]
summary (dna$Sample_ID %in% row.names(sequenced))
dna$Sample_ID <- str_replace(dna$Sample_ID , "D4526W01F59G6", "D4526MOMF59G6")
dna$Sample_ID <- str_replace(dna$Sample_ID , "D26_2M0662D4", "D4526M0662D4")
row.names(dna)<-dna$Sample_ID
dna$Sample_ID=NULL
QC<-merge(sequenced, dna, by="row.names")
names (QC) [1]<- "NG_ID"
QC_dna_ab<- left_join(QC, ab)

RD<-read.delim("~/Desktop/CS Baby Biome/ANALYSIS/CS_BABY_BIOME_RD_KN_MGS_NG_22_02_2023.txt")
RD$KN_ID[grepl("D4526W01F59G6",RD$KN_ID)]<-"D4526MOMF59G6" 
RD$KN_ID[grepl("D26_2M0662D4_",RD$KN_ID)]<-"D4526M0662D4" 
RD$KN_ID <- str_replace(RD$KN_ID  , "_", "")
summary (RD$KN_ID %in% QC_dna_ab$NG_ID) # 197 overlapping 
RD<-RD[, c(1,16, 17)]
names (RD)[1]<-"NG_ID"
QC_all<- left_join(QC_dna_ab, RD)
metadata<-QC_all
row.names(metadata)<-metadata$NG_ID
metadata$Timepoint_categorical <-substr(metadata$NG_ID, 6, 8) 
metadata$Timepoint_categorical <- str_replace(metadata$Timepoint_categorical , "WO6", "W06")
metadata$Timepoint_numeric<-metadata$Timepoint_categorical
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "W01", "1")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "W02", "2")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "W03", "3")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "W04", "4")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "W05", "5")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "W06", "6")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "M06", "26")
metadata$Timepoint_numeric <- str_replace(metadata$Timepoint_numeric , "M12", "52")
metadata$Timepoint_numeric<-gsub("MOM", NA, metadata$Timepoint_numeric)
metadata$Timepoint_numeric<-as.numeric(metadata$Timepoint_numeric)
metadata$SAMPLE_ID<-paste0(metadata$CS_BABY_BIOME_ID,metadata$Timepoint_categorical, "" )
#write.table(metadata, "QC_ALL_CS_BABY_BIOME_22_02_2023.txt", row.names = T, quote = F, sep = "\t")

```

```{r , MERGING WITH PHENOTYPIC DATA echo=FALSE}
metadata<-read.delim("~/Desktop/CS Baby Biome/ANALYSIS/QC_ALL_CS_BABY_BIOME_22_02_2023.txt")
phenotypes<-read.delim("~/Desktop/CS Baby Biome/PHENOTYPES/PHENOTYPES_CS_BABY_BIOME_23_02_2023.txt")
phenotypes$CS_BABY_BIOME_ID=NULL
all<- left_join(metadata, phenotypes)
write.table(all, "METADATA_CS_BABY_BIOME_23_02_2023.txt", row.names = F, quote = F, sep = "\t")
```

